apiVersion: v1
kind: Pod
metadata:
  name: streamlit-pod
  labels:
    app: streamlit-app
spec:
  containers:
  - name: streamlit-container
    image: my-streamlit-app:v1
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 8080
